### ISSUE TITLE
I'M sorry for bothering you Sir, Am getting INS-1 error after a C2B operation and I don't know if it is me or the m-pesa API problem, on m-pesa developers site the documentation is short and all i know about this error is that is an internal error

### ISSUE THREAD

**Issue by aleixo-fx** [abdulmueid/mpesa-php-api#9]

**Comment by abdulmueid** [comment]
Hi @aleixo-fx,

Can you share the code you've written for me to see where the problem could be?
I just ran the phpunit test suite and it worked as expected. I doubt the issue is on M-Pesa side.
Happy to help but you need to share more details, not just the error code.

Abdul

**Comment by aleixo-fx** [comment]
![venda](https://user-images.githubusercontent.com/19210598/90922531-73a1ec00-e3ec-11ea-86e5-a0e2242334c7.PNG)

(Removed config with keys)

**Comment by aleixo-fx** [comment]
Thank you for you time Sir. my code:


[image: config.PNG]
[image: venda.PNG]



Em sex., 21 de ago. de 2020 às 18:43, Abdul Mueid Akhtar <
notifications@github.com> escreveu:

**Comment by abdulmueid** [comment]
Check your reference. Remove the whitespace before T12344C. M-Pesa API is specific about References.

**Comment by aleixo-fx** [comment]
![compra2](https://user-images.githubusercontent.com/19210598/90928956-2166c800-e3f8-11ea-8722-fc00cf36b396.PNG)
I tried, still getting the same error

**Comment by aleixo-fx** [comment]
still getting the same error

Em sex., 21 de ago. de 2020 às 21:10, Abdul Mueid Akhtar <
notifications@github.com> escreveu:

**Comment by aleixo-fx** [comment]
Its Working now! Might have been packages conflict! I Restarted the project and cleaned the composer json!
